### ISSUE TITLE
Reloading loop

### ISSUE THREAD

**Issue by karafurtuna** [TrainerRoshi/Roshi-HHeroes-Trainer#12]
script works but there is a timer issue, ithink too short
-in activities works with problem , returns reload but does not do the job or takes no reward
-in harem does not collect moneys while activities job active
-active two or three jobs can not be done at the same time (as an example in league + villans or league + activities)

on the other hand places of power works perfect! well done and thanks so much

**Comment by TrainerRoshi** [comment]
Close your browser then open it again. When the script updates, it messes with all stored variables.

**Comment by TrainerRoshi** [comment]
Close your browser then open it again. When the script updates, it messes with all stored variables. Let me know if that solves your issues.
