### ISSUE TITLE
Bug Reload Loop

### ISSUE THREAD

**Issue by Dhanamerdeka** [TrainerRoshi/Roshi-HHeroes-Trainer#13]
This bug appear when i activated adventure.... it seems that the script thinks i have energy left... but when they click the adventure, i have not enough energy... and this looped....

after few hour... this happen again...
eventough i have enough energy... this app not working anymore... i think you need to update

**Comment by OldRon1977** [comment]
Hi :)

First things first, do you use the latest beta?
If so please deactivate all options except the one needed for adventure. If it still does not work, clear the cache via the debug menu and if it still does not work, please send in the debug file :)

**Comment by Dhanamerdeka** [comment]
> Hi :)
> 
> First things first, do you use the latest beta?
> If so please deactivate all options except the one needed for adventure. If it still does not work, clear the cache via the debug menu and if it still does not work, please send in the debug file :)

how to see lastest beta or anything like that?
i use from this url.... https://github.com/TrainerRoshi/Roshi-HHeroes-Trainer/raw/master/RoshiHHeroesTrainer.user.js
and if you says deactive all option except one needed for adventure...
how can i do that while the harem heroes still looping? i can't even open the menu....

**Comment by OldRon1977** [comment]
Ok :)

If you are on GitHub, you see at the top a link that says "<> code" just hit it.
After that you see above the file list a button, that says "main" hit it and choose "5.4-beta". Now you are ate the files from the beta branch :)
Choose the file "HHAuto.user.js" and it will show you the code. Now at the top right of the code, there is a button called "raw" if you hit that and you have Tampermonkey (or any other script handler) you see a install / re-install or upgrade / downgrade button, depending which version you have installed. In your case it should be re-install or upgrade. Just hit it and you are ready to go :)

For your access problem of the menu, just hit the blue menu button while it is running, at some point you should get lucky and interrupt the script and the menu is showing. But I hope that after loading the latest beta, just hit CTRL+F5 on the HH tab so it reloads the tab completely.

I hope that helps :)

**Comment by Dhanamerdeka** [comment]
sorry....
i don't understand what you mean...
are you mean, to go to code page, and then... what?

![Screenshot (1662)](https://user-images.githubusercontent.com/29838157/107873994-185b3d00-6ee9-11eb-9305-69dad99a9883.png)
this is the github on my side...
what i suppose to do...
i not seeing any beta page anywhere....

**Comment by Dhanamerdeka** [comment]
![Screenshot (1663)](https://user-images.githubusercontent.com/29838157/107874020-3fb20a00-6ee9-11eb-9b58-a470016ca845.png)

**Comment by OldRon1977** [comment]
Ok... I should have not looked into that on my phone...
I mixed up with a totally different script and I am sorry that I have confused you.
This script is kind of really old and I am not sure if it is still under development. The last update was around Feb 2019 if I see that correctly at the projects page. So I guess there won't be help regarding your problem... sorry :/

**Comment by Dhanamerdeka** [comment]
AH you mean you want me to use your script?
https://github.com/OldRon1977/HHauto/tree/5.3-beta ?
yours is 2 month old compared to this script which is only updated just last month...
so what the point you gonna says?......

**Comment by OldRon1977** [comment]
My point is, that I don't know the Roshi Trainer at all.
I just checked the project page and there it said, it was updated in 2019 the last time, but I might got that wrong.
I have no stakes at this script all.

I made a branch from the original HHAuto script, so I can fix a problem, but the main (and also the betas) are hosted here: https://github.com/Roukys/HHauto/issues, and this script is maintained a few times a week. Actually, the last update was made 2 days ago.

So, for Roshi I can't help you with an auto-loop - for the Roukys script I can :) That's all I was trying to say :)

The only thing that might be a problem is, that not all functions from Roshi can be found at the Roukys script, like auto-level-up for the girls... I hope that clears things up :)

**Comment by Dhanamerdeka** [comment]
i see....
after all, i still confuse, how you says "you didn't know roshi trainer at all" but you reply my issue IN rothi trainer github page... XD
but yeah... i think the admin just need to update this soon

**Comment by OldRon1977** [comment]
As soon as you visit a GitHub page and you "star" it, which is like a bookmark, you get notified about comments etc... Since I am quite active at Roukys and this here is rather quiet, I mixed them up. And my Android client is not that clear in showing which comment belongs to which repository, it just pasts the comments below each other... So that's the story how I got confused ;)

**Comment by Dhanamerdeka** [comment]
ahh i see....
that's your script that you mention earlier is good but sometime, the bot like... battle for gruntt for example... is not quite fast....
like... on the bot, they start fight, and back to lobby, open the gruntt, battle, and back to lobby.
compare to this roshi, they just start battle, open gruntt, over and over, i think feature, this have better logic, :)

**Comment by OldRon1977** [comment]
Yes and no... Since the last update HH mentioned to ban people using scripts or other helper. So we started simulating a more human behavior, so they will have a harder time to find us ;)

**Comment by Dhanamerdeka** [comment]
hmmm, on the nutshell. the game only detect automated from scapper game data,
so if that automated inside the nutaku client, that will be un-noticable...
and the game seems not have ref verification, so there's no point to go home, open boss, fight, and go back to home....
the roshi is better for me until now...

**Comment by TrainerRoshi** [comment]
Close your browser and open it again. If that doesn't work clear cookies and anything else related to the site. I'll add some extra error detection in the future. At the moment I'm working on auto-sorting girl teams for the club champion.
![Screenshot (61)](https://user-images.githubusercontent.com/48032437/108151308-69fbf700-70a4-11eb-934d-3f43a8adecdb.png)

**Comment by TrainerRoshi** [comment]
Close your browser and open it again. If that doesn't work clear cookies and anything else related to the site. I'll add some extra error detection in the future. At the moment I'm working on auto-sorting girl teams for the club champion.
![Screenshot (61)](https://user-images.githubusercontent.com/48032437/108151597-15a54700-70a5-11eb-99de-4489655e730c.png)

**Comment by TrainerRoshi** [comment]
You didn't reply if that solved your problem and you opened a different issue so i'm assuming everything works.
