### ISSUE TITLE
[Request] Stop current Feature

### ISSUE THREAD

**Issue by Dhanamerdeka** [TrainerRoshi/Roshi-HHeroes-Trainer#14]
I think you need to implement stop button, like.... if the trainer automated the battle and will end when the energy point empty, i think it will be great if we click the menu button
the automatic will be stop 

so we can stop the trainer when we clicked the wrong button (accidentally activated some feature)

**Comment by TrainerRoshi** [comment]
**Don't click the wrong button.** What you're asking for is impossible and would require a second webpage to control the first webpage. It's only 20 energy anyway. And fighting a troll is never a bad thing; you get rewards and progress towards leveling him up.
