### ISSUE TITLE
reloading bug

### ISSUE THREAD

**Issue by johnqewr** [TrainerRoshi/Roshi-HHeroes-Trainer#15]
it keeps reloading the page without doing any action, whether it was collecting money or progressing in the story. I am tampermonkey on firefox. i tried clearing browser cookies and history but it did not work

**Comment by TrainerRoshi** [comment]
Clear cookies, local storage, session storage, and close your browser and make sure you're on 1.15.3. Let me know if that fixes it.

**Comment by TrainerRoshi** [comment]
If you've cleared everything correctly, when you start up your browser all the options should be off. If they're not, you haven't cleared local storage and the script is trying to use values from a previous version and Chrome/Firefox aren't letting it because it's a security risk.
