### ISSUE TITLE
Collecting Money

### ISSUE THREAD

**Issue by Rodeo7743** [TrainerRoshi/Roshi-HHeroes-Trainer#17]
It is not able collect money from the last girl who provided money and it keeps re-entering harem page trying to collect but it is not able to collect for a long time and I am not able do anything else in that game because of that problem.

**Comment by TrainerRoshi** [comment]
I just tested it and got the same error. In the mean time open up developer tools > local storage > autoSalary > set it to FALSE

**Comment by TrainerRoshi** [comment]
Fixed as of 1.15.4. Thanks for letting me know!
