### ISSUE TITLE
error on HH sit now

### ISSUE THREAD

**Issue by JCDC85** [TrainerRoshi/Roshi-HHeroes-Trainer#2]
It seems HH changed something to fix a bug and it broke your script I think. Now anytime I try and load the HH site it will show for a split second and then the page goes blank and says "www.hentaiheroes.comundefined’s server IP address could not be found." anytime your script is enabled via tampermonkey in chrome and chrome-canary.

**Comment by TrainerRoshi** [comment]
Should work as of 1.10.0. Sorry about the delay.
