### ISSUE TITLE
Club - Running out of tickets cause an infinite and unstoppable loop.

### ISSUE THREAD

**Issue by The200IQ** [TrainerRoshi/Roshi-HHeroes-Trainer#21]
Just as the title declares.
This occurred to me when the script was supposed to challenge the Club Champion every 15 minutes. I only had approximately 10 tickets or less to begin with, so I expected it to stop when my account runs out of tickets.

However, what it did instead, is that it kept entering Clubs, leaving Clubs, entering Clubs, leaving Clubs and so on - in a very rapid manner.
The loop was infinite and there is no clear way to stop it.
There was no room to disable the Club feature since the script was acting way too rapidly.

**Browser:** Opera and Microsoft Edge.
**Extension:** Tampermonkey
**Website:** HentaiHeroes.com

**EDIT:** I attempted to re-install the script, but that did not help resolve the infinite loop. Seems like there is some sort of script cache saved somewhere. Is there a way to enable/disable features through Tampermonkey's console instead?
**EDIT #2:** Okay, no idea where the cache is located. Deleted the cache from AppData, uninstalled the script and uninstalled Tampermonkey, then re-installed them but the settings still persist. Which is nice and positive - but perhaps not in this scenario. I shall wait until this issue is investigated by you (Master Roshi). Thank You in advance!

**Comment by TrainerRoshi** [comment]
Thanks for the detailed ticket! Auto champions would stop if you ran out of tickets but I forgot to add that logic to auto clubs too. Oopsy. Version 1.20 works.

If you ever have any problem with any tampermonkey script do this:
![Screenshot (73)](https://user-images.githubusercontent.com/48032437/119742303-7f2bb300-be55-11eb-9186-e2a1a869b001.png)
![Screenshot (74)](https://user-images.githubusercontent.com/48032437/119742319-8652c100-be55-11eb-86a0-5d2c0a0b9308.png)

**Comment by The200IQ** [comment]
Thank You for the quick fix and the generous response.
I was wondering if there is a more direct way to reach out to you, perhaps through Discord or Telegram (if possible), to potentially discuss another matter (as in hiring for a certain task in exchange for funds, of course)?

**Comment by TrainerRoshi** [comment]
Yeah the email linked to this github: chef.roshi@gmail.com
