### ISSUE TITLE
Bug place of power

### ISSUE THREAD

**Issue by levieira25** [TrainerRoshi/Roshi-HHeroes-Trainer#22]
![bug place of power](https://user-images.githubusercontent.com/86177467/122833532-85ca1080-d2c3-11eb-8f66-3f1210eee066.png)

não encontra garotas para missao

**Comment by TrainerRoshi** [comment]
Atualize para a versão 1.26. Excluir "Local Storage" se ainda há um problema.
![Clear_LocalStorage](https://user-images.githubusercontent.com/48032437/122973241-0427c080-d35f-11eb-8bda-96f65e8c93bd.png)

**Comment by levieira25** [comment]
Funcionou, Resolvido.
Muito obrigado!
