### ISSUE TITLE
Trainer Size Issue

### ISSUE THREAD

**Issue by blardiarg** [TrainerRoshi/Roshi-HHeroes-Trainer#23]
For some reason, the updated version 1.26 of the trainer is zoomed in. When I open the settings all I see is where to go and to the right a little box that says "Master Roshi's Trainer". I have to zoom out to 33% screen size just to see the sliders but it doesn't tell me what they're for. Any advice on how to fix this? This is what I see when I open the menu: https://ibb.co/cC1x1jH

**Comment by TrainerRoshi** [comment]
Fixed as of 1.27. Let me know if anything else is out of place. I had to move some buttons too.
