### ISSUE TITLE
I am stuck on the Places of Power Screen

### ISSUE THREAD

**Issue by Cyarutchiii** [TrainerRoshi/Roshi-HHeroes-Trainer#24]
Title says it all. I reload the page, it instantly navigates to Places of Power again. Can't leave, because the menu isn't shown while I am there.

**Comment by TrainerRoshi** [comment]
Update to version 1.27. If it still doesn't work, clear your Local Storage:

![Clear_LocalStorage_arrows](https://user-images.githubusercontent.com/48032437/123522501-9bf11b80-d68b-11eb-85ce-11f2321ebaf6.png)

In Local Storage, you can also manually turn options on and off without using the menu.

**Comment by Cyarutchiii** [comment]
Thanks a lot, works fine now :)
