### ISSUE TITLE
Issue using Places of Power

### ISSUE THREAD

**Issue by xFATALISTx** [TrainerRoshi/Roshi-HHeroes-Trainer#25]
Hello. I added script to act in Places of Power (7 hours using girls power), but I'm not having Heroes University open, so even though it opens the page, it doesn't go any firther, however the script button is also gone
![2021-06-27_18-48-37](https://user-images.githubusercontent.com/86564829/123550941-51010200-d778-11eb-9816-cdf6cc131dbe.png)

**Comment by xFATALISTx** [comment]
Any way to set default settings of script so that I could use other script possibilities?

**Comment by TrainerRoshi** [comment]
Update to version 1.27. If that doesn't fix the issues, delete Local Storage:

![Clear_LocalStorage_arrows](https://user-images.githubusercontent.com/48032437/123551472-e92ec500-d73f-11eb-8502-c84182b4b0de.png)

In Local Storage you can also manually set options when the menu isn't visible.
