### ISSUE TITLE
suggest

### ISSUE THREAD

**Issue by Dhanamerdeka** [TrainerRoshi/Roshi-HHeroes-Trainer#26]
well thanks for updating the script..... until this day
btw i think you should add some description on your github page. so anyone who searching hentai heroes or harem heroes can find it right when they type on github

**Comment by TrainerRoshi** [comment]
What happened today?
Thanks for the tip about descriptions! How did you find my script, Youtube?

**Comment by Dhanamerdeka** [comment]
well for fact, i already use your script long time ago... maybe first time you share that on youtube (delay 2 month)
but after that my laptop just broke, and i lost all of the data....

now even i have new laptop... i forget the script name and now i find it again...
that's why i suggesting it to you

since you just have "Roshi-HHeroes-Trainer" and it's very hard to search....
i found your github after digging on youtube... since your lastest video doesn't have any link to your github..

maybe if i can suggest something to you
1. place github link on any video you made
2. create some basic tutorial for new people... well i know chrome for along time, so i already knew how to use your script... 
but maybe for new people they didn't even know how to use userscript...

so maybe that two suggestion for you

**Comment by TrainerRoshi** [comment]
Maybe you should subscribe to my YouTube channel. Or maybe you should donate a sandwich so Roshi will keep updating the script for you ;)

**Comment by Dhanamerdeka** [comment]
XD sure
