### ISSUE TITLE
Champions not working properly

### ISSUE THREAD

**Issue by NineNein99** [TrainerRoshi/Roshi-HHeroes-Trainer#29]
when checking the champions option, instead of going to selected champions it goes to reception instead and automatically disables its option but making no progress. 

idk if I'm doing it right but I can't figure how it works

**Comment by TrainerRoshi** [comment]
Before anything, it goes to check if you have any tickets. If you have less than 33 tickets, it turns off. Open the console and see what the error message is.
![Screenshot 2021-08-28 152714](https://user-images.githubusercontent.com/48032437/131228772-f191c4b5-c41e-40f2-9345-b4cea2b63463.png)

**Comment by TrainerRoshi** [comment]
Okie dokie. I assume you figured it out. Reopen this issue if you still have problems.
