### ISSUE TITLE
Page constantly reloading when turning on Blessings in Comix Harem

### ISSUE THREAD

**Issue by SpeedDemon92** [TrainerRoshi/Roshi-HHeroes-Trainer#30]
I accidentally turned on blessings in Comix Harem and now the page wont stop reloading. Is there any way for me to turn it off to get it working properly again?

**Comment by TrainerRoshi** [comment]
I'm working on it. In the mean time you should: 
![Screenshot 2021-09-01 131747](https://user-images.githubusercontent.com/48032437/131715374-ed364813-1035-4d9c-b491-f67fb2df6e71.png)

**Comment by TrainerRoshi** [comment]
Ok. Fixed as of 1.39.

**Comment by TrainerRoshi** [comment]
Okie dokie. I assume you're happy. If not, reopen the issue.
