### ISSUE TITLE
champions issue

### ISSUE THREAD

**Issue by Khosronejad** [TrainerRoshi/Roshi-HHeroes-Trainer#31]
can't count the tickets and champions fight don't work

**Comment by Khosronejad** [comment]
![Screenshot 2021-10-29 at 23-50-46 Hentai Heroes](https://user-images.githubusercontent.com/93334670/139497178-378fb1bd-af64-4faa-a149-1e49acc8a4c9.png)

**Comment by TrainerRoshi** [comment]
Try turning off the other script you're using.

**Comment by Khosronejad** [comment]
thanks, my bad.
it works fine
