### ISSUE TITLE
champion fights and ticket counts

### ISSUE THREAD

**Issue by Khosronejad** [TrainerRoshi/Roshi-HHeroes-Trainer#32]
Dear Master roshi
i reported champion fights fail before and you advised for removing any other scripts. i did and i seemed it solved the problem but unfortunately the problem still remained. 

trainer cant count fights ticket and fails for auto fights for champions.

**Comment by Khosronejad** [comment]
![Screenshot 2021-11-05 at 16-28-01 Hentai Heroes](https://user-images.githubusercontent.com/93334670/140514640-c4613003-001e-4f19-852a-9e57a1a87bb6.png)

**Comment by TrainerRoshi** [comment]
It counts the tickets when it actually visits a page which shows the number of tickets. I set it to stop fighting if you have 10 tickets or fewer. The message in the console should say `"You need more tickets!"` Let me know if that helps.

**Comment by Khosronejad** [comment]
I have 73 tickets right now and i'm useing firefox. it was fine before so i removed cleared saved files and cookies from setting for www.hentaiheroes.com ,but didn't help.

**Comment by TrainerRoshi** [comment]
What does the console say?

**Comment by Khosronejad** [comment]
![Screenshot 2021-11-10 201303](https://user-images.githubusercontent.com/93334670/141160031-b7290f41-371a-4db8-9037-77bce9f98b0d.png)

**Comment by Khosronejad** [comment]
wooooooooow!!!!!!!!!!!!!!!!!!!!!!!!
what is this?????

**Comment by TrainerRoshi** [comment]
Is it fixed? I had to publish two updates today (1.46 and 1.47) just to correct for all the pointless changes they made to their own code.

**Comment by Khosronejad** [comment]
the great master you are the best. now every thing is in right order.


except still no count for champions fight and no auto fight

**Comment by Khosronejad** [comment]
![Screenshot 2021-11-11 at 10-30-51 Hentai Heroes](https://user-images.githubusercontent.com/93334670/141252777-f265e49b-258a-4e2e-825a-2feba65735f7.png)

**Comment by Khosronejad** [comment]
surprise , I forced champion for several times and it started to work fine. 
just for you knowledge

**Comment by Khosronejad** [comment]
![Screenshot 2021-11-11 at 12-42-36 Hentai Heroes](https://user-images.githubusercontent.com/93334670/141270742-1549df8e-f05e-47c1-8299-921bd8dddd93.png)

**Comment by Khosronejad** [comment]
![Screenshot 2021-11-11 at 12-45-38 Hentai Heroes](https://user-images.githubusercontent.com/93334670/141271185-2c6d422a-3e40-4374-80e0-0c1aa81d067f.png)

**Comment by TrainerRoshi** [comment]
Thanks for letting me know. I tried to force an error ever since your first post but in my case it always worked. If you're on chrome you can do `CTRL + SHIFT + i` and open the CONSOLE tab. I add a lot of useful information there. Under the APPLICATION tab you can delete Local Storage and Session Storage in case my script does something silly again.

**Comment by Khosronejad** [comment]
Kind master, Thank you again.
I use firefox and i have tested clearing stored data for several times but it doesn't help.
i accidentally found that, when the count is "?" if you manually start a champion fight the counter starts doing well.

**Comment by kkhosronejad** [comment]
Dear Master
I think there is a problem with collecting money. for both "Hentai Heroes" and " Comix Harem"

**Comment by TrainerRoshi** [comment]
Yes, you're right. They changed something again. I'll fix it.

**Comment by kkhosronejad** [comment]
Master , your magic works fine

**Comment by LucasViacava** [comment]
@TrainerRoshi Master, i'm pretty happy with your script, and it works like magic, but i encountered a problem with fighting champions, i have 23 tickets but it says that i need more tickets. Thank you so much for your work 
![image](https://user-images.githubusercontent.com/85575883/142706761-f88d5876-33ea-49ac-a7ce-11a25a0006bd.png)

**Comment by TrainerRoshi** [comment]
Yeah I just checked my script. I used the same error message if you run out of free drafts while sorting your girls. Oopsy. It looks like it works though. If it says "script started" that means it's working fine. Also I set it to a minimum of 10 tickets just to prevent running out.
