### ISSUE TITLE
Master Roshi's HHeroes Trainer Error

### ISSUE THREAD

**Issue by AaronTylerBerry** [TrainerRoshi/Roshi-HHeroes-Trainer#33]
The trainer script window is meshed in with the game window. I've tried disabling and re-enabling the script Tampermonkey, and the page doesn't go back to normal.

Here's a picture to show what I'm talking about.

![2021-11-11 at 21-41-06](https://user-images.githubusercontent.com/92951602/141399896-53ea9b69-745c-4369-b67c-e2f46b9c3e62.jpg)

**Comment by Eznemazajatek** [comment]
Same happens for me too.

**Comment by TrainerRoshi** [comment]
Make sure you update to version 1.47. And if that still doesn't work:
![Clear_LocalStorage_arrows](https://user-images.githubusercontent.com/48032437/141511225-ea23268f-e4ab-4e65-a4ec-7fcd44c6a468.png)

**Comment by Eznemazajatek** [comment]
> Make sure you update to version 1.47. And if that still doesn't work: ![Clear_LocalStorage_arrows](https://user-images.githubusercontent.com/48032437/141511225-ea23268f-e4ab-4e65-a4ec-7fcd44c6a468.png)

This fixed it for me Thank you!

**Comment by AaronTylerBerry** [comment]
I'm not getting the console on the left like you're showing!
![2021-11-14 at 17-57-02](https://user-images.githubusercontent.com/92951602/141702085-bd1d1d9c-46a3-4c66-95d9-ca33a8c1995d.jpg)

But I do have v.1.47

**Comment by AaronTylerBerry** [comment]
I've also deleted the script, and re-downloaded it, and I still get the same error! :(

**Comment by AaronTylerBerry** [comment]
I just found v.1.48, and after installing it, I'm getting this error!

I'm guessing, it's a problem with the website?? Do you think they've seen me with the script, and they are keeping me from using it?

Just a thought!

**Comment by TrainerRoshi** [comment]
Click the STORAGE tab and delete Local Storage.

**Comment by AaronTylerBerry** [comment]
I found where you told me to clear the data, but Hentai Heroes is still getting the error, but Comix Harem is working properly now!

**Comment by mudasir370** [comment]
![Screenshot 2021-11-15 at 17-05-48 Nutaku net Online games](https://user-images.githubusercontent.com/79626383/141779787-ddbe4b49-d2bc-416f-a498-cb47bfb02ee1.png)
Tried above solution but did not work for me

**Comment by TrainerRoshi** [comment]
Try closing your browser and opening it again.
