### ISSUE TITLE
HH Screen Error

### ISSUE THREAD

**Issue by mudasir370** [TrainerRoshi/Roshi-HHeroes-Trainer#34]
![Screenshot 2021-11-15 at 17-05-48 Nutaku net Online games](https://user-images.githubusercontent.com/79626383/141780791-e72314c7-83fa-40d5-aa07-2d3bd385bb0a.png)
Screen is jumbled. Script not working. Also tried disabling other scripts. Comix Harem is working fine. Tries multiple browsers.

**Comment by TrainerRoshi** [comment]
Update to 1.48 and try this. If you're on Nutaku, do the same thing but refresh the page a few times after you open the developer console:
![Clear_LocalStorage_arrows](https://user-images.githubusercontent.com/48032437/141832265-5aff5681-11d0-4efb-8e2e-453cf57af1c6.png)

**Comment by TrainerRoshi** [comment]
This is what you need to see and clear for Nutaku.net : 

![Screenshot 2021-11-15 130945](https://user-images.githubusercontent.com/48032437/141832692-bc00d759-d3dc-4c60-aabe-3cef0ea72f5e.png)

**Comment by mudasir370** [comment]
Finally worked. Thanks for assist.
