### ISSUE TITLE
Glitch

### ISSUE THREAD

**Issue by CaragiaDumitru** [TrainerRoshi/Roshi-HHeroes-Trainer#36]
I also have a problem, my Master Roshi's trainer doesn't work properly anymore, when it's turned on, some icons disappear from the game, besides that, my Master Roshi's face appears in Town, in short, the whole game is a glitch.
I HOPE YOU UNDERSTAND THE MESSAGE AND THAT YOU TRY TO REMEDY IT WITH AN U
![Untitled](https://user-images.githubusercontent.com/94554190/142246199-0bdedf55-da42-491b-babb-40f25206c13e.png)
![Untitled](https://user-images.githubusercontent.com/94554190/142246245-f586b778-05d6-402f-be82-bf1e504dfcad.png)

**Comment by TrainerRoshi** [comment]
Nu te ajută un update. Deja am făcut un update de la 1.47 la 1.48 și problema a rămas. Dacă nu ștergi Local Storage nu va funcționa..
![Clear_LocalStorage_arrows](https://user-images.githubusercontent.com/48032437/142268395-03d17ea5-7ea1-48c6-b32b-bb34883f9e95.png)
