### ISSUE TITLE
Champion Sorting Algorithm

### ISSUE THREAD

**Issue by TrainerRoshi** [TrainerRoshi/Roshi-HHeroes-Trainer#37]
Salut Master,
Nouveau petit retour d'expérience, qui pourra peut-être t'aider à peaufiner ton algoritme.
J'organise moi-même mes filles contre le champion du club, et je m'arrête alors qu'il me reste encore 2 tirages possibles, parce que je me dis qu'il faudrait quand même beaucoup de bol pour avoir mieux que ce que j'ai : 
<img width="519" alt="Capture d’écran 2021-12-13 à 13 39 26" src="https://user-images.githubusercontent.com/66478816/145815178-3bd76fc2-0d3b-445f-9d27-7636253f13a5.png">

Ensuite, je lance ton script en espérant qu'il se contente de ce que j'ai, mais non, il utilise 1 autre tirage (il en reste donc encore 1) et voilà ce que cela donne (et il a eu du bol de tomber sur une fille de 38K) :
<img width="519" alt="Capture d’écran 2021-12-13 à 13 40 11" src="https://user-images.githubusercontent.com/66478816/145815071-b22360a0-7935-467e-a7ef-42efdabe02da.png">

_Originally posted by @Iohannulus in https://github.com/TrainerRoshi/Roshi-HHeroes-Trainer/issues/19#issuecomment-992443918_

**Comment by TrainerRoshi** [comment]
Tu as raison. Mais les cinq premières filles sont cependant plus importantes. Je n'ai jamais atteint la 10e fille lors d'un combat par exemple. Je pense que la deuxième équipe fera plus de dégâts lors d'un combat ; à moins que tu ne sois niveau 490+

**Comment by Iohannulus** [comment]
Oui, c'est vrai, ça n'atteint pas toujours la 10ème fille, mais cela m'arrive quand même (je suis niveau 419), tout dépend du nombre de fois où la position préférée de la fille du champion se présente.

**Comment by TrainerRoshi** [comment]
Essayez 1.52. J'ai ajouté le bouton `SORT ✅`. Désolé du retard. Bonne année!

**Comment by Iohannulus** [comment]
Merci beaucoup Master, c'est super sympa ! Excellente année à toi !

**Comment by Iohannulus** [comment]
C'est la 1.51, non ?

**Comment by TrainerRoshi** [comment]
Oui oui. 1.51. Oops.
