### ISSUE TITLE
The bot is too fast

### ISSUE THREAD

**Issue by HaremHero** [TrainerRoshi/Roshi-HHeroes-Trainer#38]
Hey!

I think the bot acts too fast and having trouble when the non-optimized game loads 100s of images:
- It leaves random amount of purchasable items in the Market.
- In halfway of Places of Power assignment it freezes the browser and cannot move forward so it keeps the processor busy and consume a lot of real power.
- Nutaku HH having 500 Internal Server Error like 4 times a day, which is strange given that we make the server very busy.
- What about a potential banhammer?

I think the bot needs to be more human-like in terms of speed so all the above issues would be solved.

**Comment by TrainerRoshi** [comment]
True. I think most of the issues are with Comix Harem. If I just run my script simultaneously on https://www.hentaiheroes.com/ and on https://www.nutaku.net/games/harem-heroes/play/ it works fine. 

Except for Places of Power; I've been trying to fix the freeze issue for two years. If you use a chrome app that automatically refreshes the page, every hour for example, you won't notice any problems.

The Market works as intended. I made it that way to avoid a banhammer. It buys what it can in a few seconds and then it'll go back in an hour. It always buys every item in the end.

The game is even worse than you think. Every time you go to the Tower of Fame, it downloads a 7MB text variable with every single opponent and all their girls, etc. And if you click on an opponent's portrait, it downloads another 15MB with every possible girl image and background just so it can display that image with the hero and his girls.

**Comment by HaremHero** [comment]
> chrome app that automatically refreshes the page

I have made one back then, but sometimes the PoP freezes twice which means 2 hour of extreme CPU cycling. I have started using the other famous script HH++ and now your script crashes the page after a while, rather keeping the CPU busy: I have no idea why, but it saves some electricity.

---

> The Market works as intended. [...] It always buys every item in the end.

It happens sometimes via/without HH++, I am sure:

![book](https://user-images.githubusercontent.com/96337465/148654503-1165f734-b699-4dc7-9e1c-593084446a7b.png)
![gift](https://user-images.githubusercontent.com/96337465/148654509-4741b704-41d9-48cb-950d-d765e3cd7467.png)

I think it could use the pattern to do the buying task twice, like the activities task dispatching twice for each activity. For me everything working for the first time, but the Market.

---

> The game is even worse than you think.

Is there no way we could refuse all the image/text downloads and make the bot/game run faster?

**Comment by TrainerRoshi** [comment]
I wish I could make the game run better. A few months ago I tried to rewrite my script so it doesn't navigate the page at all; it would just send server requests back and forth. But I realised I am not a good enough programmer to do that. I learned javascript for the first time while creating this script :-) 
My market script really does buy three times. Check the market when _New stock in:_ is less than an hour. You'll see everything is bought. 
You can turn my PoP off if the HH++ does it better. I'll fix it eventually when I figure out what I'm doing wrong or where it hangs. I even added comments to every single step of my test code and I still couldn't see why it freezes. I blame gremlins.

**Comment by HaremHero** [comment]
Nah, HH++ do not add any "hack" to the game and very well-known players written it.

> server requests back and forth

When they would introduce a new server request variable, they would immediately detect the bannable folks, so the click-based/human-like approach is way more better.

> My market script really does buy three times.

Okay, but it is not that human-like approach. Thanks for the clarification! Keep up the great work!
