### ISSUE TITLE
ComixHarem - Champions have been added!

### ISSUE THREAD

**Issue by The200IQ** [TrainerRoshi/Roshi-HHeroes-Trainer#39]
Champions have been added as a new feature on ComixHarem. It is exactly similar to HentaiHeroes.

There are only two Champions in the game right now on ComixHarem.
The Roshi Champions feature from HentaiHeroes is currently not functional (at least not properly) in ComixHarem.

**Browser:** Google Chrome.
**Extension:** Tampermonkey
**Website:** ComixHarem.com

Thank you Roshi. <3 You are truly the absolute best.

**Comment by TrainerRoshi** [comment]
I'll look into it. <3
