### ISSUE TITLE
Champion feature doesn't work since last update

### ISSUE THREAD

**Issue by pagauvreau** [TrainerRoshi/Roshi-HHeroes-Trainer#4]
Hi, 
The Champions Perform button changed (adding an option of multiple combat in once)

Thanks for your nice script!

tested on Nutaku, on Chrome
![champion](https://user-images.githubusercontent.com/10059816/73837188-f2cc2b80-47de-11ea-99a3-faedbb641433.jpg)

**Comment by KevoNeo** [comment]
Hi, When I enable champions, the script keeps checking them even though I don't have any tickets.
It basically keeps looping: Main page > Champion page > Page of specific champions I selected > Main page (when the script sees i don't have any champion tickets), Could you check that detail please. Beforehand thank you very much
