### ISSUE TITLE
The "Activities" feature broke after the new release!

### ISSUE THREAD

**Issue by The200IQ** [TrainerRoshi/Roshi-HHeroes-Trainer#40]
Kinkoid released a new feature called "Daily Goals" for their games.
This new feature is located in the "Activities" tab and has therefore impaired the "Activities" script (including the "Places of Power" script).

**Comment by TrainerRoshi** [comment]
Fixed as of 1.52. I'll add some system to collect the rewards from that new daily nonsense soon.
