### ISSUE TITLE
Objetivos Diarios y Misiones

### ISSUE THREAD

**Issue by Pandx0** [TrainerRoshi/Roshi-HHeroes-Trainer#41]
Buen día. :)
Al entrar al apartado de las actividades se cierra y abre repetidamente en los objetivos y no realiza las misiones.

**Comment by TrainerRoshi** [comment]
Try clearing local storage ([Instructions](https://user-images.githubusercontent.com/48032437/141511383-46807a16-a918-4b73-ba02-f9873f745a17.png)). Also try closing your browser and opening it again.
