### ISSUE TITLE
mouse movement Pase

### ISSUE THREAD

**Issue by kkhosronejad** [TrainerRoshi/Roshi-HHeroes-Trainer#42]
Dear master
pause the script by mouse movement is a nice thing to adjust the game manually, but sometimes it becomes annoying as you are just checking the game or you want to do something in other windows.

is it possible to add a slide or radio bottom in your menu to be selective by the user?

**Comment by TrainerRoshi** [comment]
Umm mouse movement only applies to that specific page. If you go on any other tab or minimize the window the script obviously still runs.
