### ISSUE TITLE
Few problems

### ISSUE THREAD

**Issue by Eznemazajatek** [TrainerRoshi/Roshi-HHeroes-Trainer#44]
Hey,
Since the latest update there are a few issues that came up.
First: when you fight in the leagues the script stops at 3 fight against an enemy and it wont start a new fight until you manually attack someone.
Second: It wont buy everything from the shop.
Third: It crashes the website or they have came up with some solution against scripts because after a while of using a script the website comes up with this message: Oh my! There is a problem here. I reported it to my little geeks and they'll fix it. Very sorry!
I hope this is fixable.
Thanks

**Comment by TrainerRoshi** [comment]
Clear local storage and close your browser.

**Comment by Eznemazajatek** [comment]
>
Fixed every issue on pc, but the problem still exists on my chrome os tablet. Any idea?
I now know for sure what option breaks the site too. It's the troll fighter option.

**Comment by TrainerRoshi** [comment]
If it works on your PC than I don't understand your problem. Post a video, screenshots, the console log, etc.

**Comment by Eznemazajatek** [comment]
> If it works on your PC than I don't understand your problem. Post a video, screenshots, the console log, etc.

![image](https://user-images.githubusercontent.com/53662362/170802485-c87252dc-f9d1-436c-a15a-478ba4b46a36.png)
This happens when i turn on the troll fighter option

**Comment by TrainerRoshi** [comment]
Yeah it's trying to go to a troll that doesn't exist. Clear your local storage. I'll add some more fail-safes in the next update. Sorry about that.

**Comment by Eznemazajatek** [comment]
That's great I'll just stop using that option on the chrome os for now.
Thanks for your patience and the help.
