### ISSUE TITLE
Oh my! There is a problem here. I reported it to my little geeks and they'll fix it. Very sorry!

### ISSUE THREAD

**Issue by leohqr** [TrainerRoshi/Roshi-HHeroes-Trainer#45]
![Captura de tela 2022-06-03 121533](https://user-images.githubusercontent.com/101412840/171882717-e26aea32-5d46-4b46-9125-e330c844175e.png)

On the console: 
![ss](https://user-images.githubusercontent.com/101412840/171882759-0e1193eb-6c71-4f93-a31c-a848329f104a.png)

I already deleted the browsing history, but it didn't solve the issue.

**Comment by TrainerRoshi** [comment]
Browsing history doesn't do anything. [**Do this**](https://user-images.githubusercontent.com/48032437/141511383-46807a16-a918-4b73-ba02-f9873f745a17.png) and close your browser entirely. Chrome updates usually break something temporarily.
