### ISSUE TITLE
white screen and error

### ISSUE THREAD

**Issue by Sigmarkin** [TrainerRoshi/Roshi-HHeroes-Trainer#47]
When you chose "troll fighter" and selecting a troll after script starts battle it all immidiatly go to white scrin with bunny face and says "There is a problem i'll say to my geeks and they fix it"

Also only a clearing with dev. tools help to go back to game but it didn't solve the prublem if once turn on "troll fighter"

**Comment by TrainerRoshi** [comment]
So sorry guys. I fixed this issue in the May 27th update but it didn't get published. Try the latest version, 1.58, I uploaded today. I'll check the issues section more often. Sorry again :'(
