### ISSUE TITLE
money collect vs places of power 

### ISSUE THREAD

**Issue by kkhosronejad** [TrainerRoshi/Roshi-HHeroes-Trainer#48]
Dear Master
I have a suggestion for better permanence. now "places of powers" routine doesn't starts unless money collecting has been finished and as the browser is not on top, money collecting can takes so long therefore there is a huge loss of time.
if the priority of "powers of places" be like villian combat , money collecting doesn't stop rewards of "powers of places".

thanks in advance

**Comment by TrainerRoshi** [comment]
Hi, I'll look into it. I left the auto salary option for people just starting the game with less than 100 girls. After that, the best source of money is _Pachinko x10_ and sell the items. One green item sells for more than the salary collected from 1,000 girls for example. I'll move _places of power_ to the highest priority in the next update. Thanks for letting me know.

**Comment by kkhosronejad** [comment]
thanks master
