### ISSUE TITLE
Make new features optional

### ISSUE THREAD

**Issue by haremhero69** [TrainerRoshi/Roshi-HHeroes-Trainer#49]
> Salary is auto-collected on the Home page if it's free to collect

Currently the script collects less than 1000 Ymens every minute which is not really human-like if you have the game opened 24/7. I think the already existing money collecting feature should use the Collect-button if available with the given thresholds to make it less bot-like and toggleable. Also as a human-being you smash that button at most 4 times a day, so it would be nice to increase the slider to activate the money collection in an hourly manner, like every 6 hours.

Please make the reward auto-collecting optional. The Platinum card collects the rewards when you log in while a contest is active, which can win a contest here-and-there, e.g. the XP rewards for the first day of Legendary Contests. (I think it is a bug, and not a feature, wink-wink)

I assume people already use other scripts for the UI features (e.g. Tom's), which results in:
![timers overlap](https://user-images.githubusercontent.com/82240365/190899216-5581bd9d-4426-4f18-b3e2-1a7f97a6cd5a.png)
Of course you cannot toggle this timer feature separately using the other scripts!

**Comment by TrainerRoshi** [comment]
I don't recommend auto collecting salary at all. I almost removed the feature from my script in 1.60. Kinkoid is obsessed with preventing new players from starting this game.

> Please make the reward auto-collecting optional.
The auto collection of Seasons and the two Paths happens during the last 12 hours of each. My script doesn't collect from events.

> Tom's
That clock looks ugly. But I'll add a toggle button somewhere next update; probably Roshi's penis.
