### ISSUE TITLE
Max stats UP to 500

### ISSUE THREAD

**Issue by dude29300** [TrainerRoshi/Roshi-HHeroes-Trainer#5]
Can you UP max stats upgrade to 500 ?
I have the data
![Girls-0-500](https://user-images.githubusercontent.com/60757476/73976828-6a0dd680-4929-11ea-846e-a70d6681e26a.png)

**Comment by TrainerRoshi** [comment]
Fixed as of 1.10.0. Love the graph! Wish I had seen it earlier. It took me a few hours to figure out the formulas.
