### ISSUE TITLE
Giant Master Roshi Face

### ISSUE THREAD

**Issue by MrJackle00** [TrainerRoshi/Roshi-HHeroes-Trainer#51]
Hello, I wanted to address a bug about the giant master Roshi face showing up, and the trainer stops working, and the thing is this has happened before when Hheroes updated there stuff but I figured you already knew about this bug but I just wanted to address it if not, but hope it gets fixed its honestly helpful when I play so thank you.

![Master Roshi's Face](https://user-images.githubusercontent.com/116324133/197092256-c9878dd7-f839-482c-b384-d40705c5ac06.JPG)

**Comment by TrainerRoshi** [comment]
Fixed as of 1.60. Sorry about the delay.

**Comment by kkhosronejad** [comment]
thanks master. your done great
