### ISSUE TITLE
Collecter l'argent ne fonctionne plus

### ISSUE THREAD

**Issue by westjasper974** [TrainerRoshi/Roshi-HHeroes-Trainer#52]
La fonction "collecter l'argent auto" ne semble plus fonctionner, le script s'exécute bien, mais l'argent n'est pas crédité sur le compte.
De plus sur la version expérimentale, même quand on désactive l'option qui collecte l'argent, l'argent est quand même collecté sans être créditer sur le compte.

**Comment by TrainerRoshi** [comment]
![Screenshot 2022-10-29 143209](https://user-images.githubusercontent.com/48032437/198847442-07344d98-fdbc-4066-afc6-455411ab8cea.jpg)
Ce? Il fonctionne pour moi. Poster une capture d’écran. Tout d’abord, fermer et rouvrir ton navigateur.

**Comment by westjasper974** [comment]
Oui, ça marche à nouveau.
C'est bizarre, pendant presque 24h l'argent était collecté, mais pas crédité sur le compte. 
Je ne sais pas pourquoi ça faisait ça, j'ai pourtant testé sur 2 navigateurs différents, le bug persistait.
Tant mieux si ça remarche tout seul.
