### ISSUE TITLE
Where to activate it / change the settings

### ISSUE THREAD

**Issue by Ha6ay** [TrainerRoshi/Roshi-HHeroes-Trainer#55]
I have Tampermonkey installed, and the script is activated, but i cant seem to find the settings button for it on HaremHeroes / Pornstar Harem. Am I just blind or where do i find it? (A Picture would be nice). Bzw Usind Opera as the Browser of Choice (didnt work on Chrome either)

**Comment by Dhanamerdeka** [comment]
same... not working on my side

**Comment by Dhanamerdeka** [comment]
the icon trainer roshi will be on the corner of the game
for activating it just toggle it and leave it a while
they will do the job after you idle few second....

i also had suggestion to the author of the script to add some hotkey to instant do the job or make it faster....
unlike now

**Comment by Ha6ay** [comment]
Thats the Problem, i cant seem to find / see the button, the script is activated and i am on said Websites

**Comment by Ha6ay** [comment]
> the icon trainer roshi will be on the corner of the game for activating it just toggle it and leave it a while they will do the job after you idle few second....
> 
> i also had suggestion to the author of the script to add some hotkey to instant do the job or make it faster.... unlike now

^

**Comment by Ha6ay** [comment]
Edit: It works now after is deleted itself and i reinstalled it with Harem Heroes but not with pornstar Harem

**Comment by TrainerRoshi** [comment]
Porn Star Harem should work as of 1.63. I still need to add checks for users under level 20, so try not to turn on things which don't exist. Sorry about the delay!
