### ISSUE TITLE
pornstar harem loop not working

### ISSUE THREAD

**Issue by RussellBai** [TrainerRoshi/Roshi-HHeroes-Trainer#56]
pornstar harem loop not working, and can't save setting.

> jquery.min.js:2 jQuery.Deferred exception: Cannot read properties of undefined (reading 'amount') TypeError: Cannot read properties of undefined (reading 'amount')
>     at autoLoop (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Master%2520Roshi's%2520HHeroes%2520Trainer.user.js&id=006a246a-92fa-4fc9-af6d-516113f1a2b0:290:291094)
>     at Object.mMOoq (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Master%2520Roshi's%2520HHeroes%2520Trainer.user.js&id=006a246a-92fa-4fc9-af6d-516113f1a2b0:290:314250)
>     at HTMLDocument.start (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Master%2520Roshi's%2520HHeroes%2520Trainer.user.js&id=006a246a-92fa-4fc9-af6d-516113f1a2b0:290:341139)
>     at e (https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js:2:30038)
>     at t (https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js:2:30340) undefined
> S.Deferred.exceptionHook @ jquery.min.js:2
> ContentScript.js:112 Exception in onResRdy: TypeError: Cannot read properties of undefined (reading 'htmlRes')
> jquery.min.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'amount')
>     at autoLoop (userscript.html?name=Master%2520Roshi's%2520HHeroes%2520Trainer.user.js&id=006a246a-92fa-4fc9-af6d-516113f1a2b0:290:291094)
>     at Object.mMOoq (userscript.html?name=Master%2520Roshi's%2520HHeroes%2520Trainer.user.js&id=006a246a-92fa-4fc9-af6d-516113f1a2b0:290:314250)
>     at HTMLDocument.start (userscript.html?name=Master%2520Roshi's%2520HHeroes%2520Trainer.user.js&id=006a246a-92fa-4fc9-af6d-516113f1a2b0:290:341139)
>     at e (jquery.min.js:2:30038)
>     at t (jquery.min.js:2:30340)

**Comment by TrainerRoshi** [comment]
Try 1.63.
