### ISSUE TITLE
Champions stuck

### ISSUE THREAD

**Issue by sirdragon33** [TrainerRoshi/Roshi-HHeroes-Trainer#57]
Good afternoon!

Previously after you have fought the Champion the game would go back to title screen or to next operation. Now, as long as you have champion fights activated in the trainer it would be stuck at the champion page no matter if there is a timer for next attempt (15 mins) or you have beaten him and wait for the next stage (24 hrs), preventing other commands from execution. Have this problem both at CH and HH.

**Comment by TrainerRoshi** [comment]
Fixed as of 1.66. They changed a lot of stuff on the website. Let me know if you see any other bugs.

**Comment by kkhosronejad** [comment]
Thanks Master but club champion still has the same problem

**Comment by sirdragon33** [comment]
> Fixed as of 1.66. They changed a lot of stuff on the website. Let me know if you see any other bugs.

Chacked that, fixed indeed, thanks a lot!

**Comment by TrainerRoshi** [comment]
> Thanks Master but club champion still has the same problem

Got it. Fixed as of 1.67.
