### ISSUE TITLE
Chests collection at Activities

### ISSUE THREAD

**Issue by mds031** [TrainerRoshi/Roshi-HHeroes-Trainer#58]
Hi Roshi,

Could you make the chests collection as optional at the activities, please? 

![2023-04-30_171726](https://user-images.githubusercontent.com/132217764/235364126-7449a2b8-5b5c-4737-a61e-8e916706c85a.png)

Thank you so much!

**Comment by TrainerRoshi** [comment]
Yeah I thought about it. I just turn it off at the end of the month when I'm doing that event. But then I can forget to turn it back on. It's only 6 fights and 8,525 experience. I don't think it's worth the hassle of having a separate button which can break the script if it fails.

**Comment by Sarewe** [comment]
I would also like it if it were separated. The problem is, not only the chests are collected, but also the profits from the contests.

**Comment by TrainerRoshi** [comment]
Ah I see the issue now Sarewe. But then what happens if you don't collect the reward? Do you lose it after a week?

**Comment by Sarewe** [comment]
At some point the profit is lost, but that takes a long time. Much longer than a week.
For me it has the advantage that I can use the profit from the competition later. If I win a fight, I don't need it immediately. But there are often competitions and then you are happy when you have a few fights.

**Comment by TrainerRoshi** [comment]
Okie dokie. I'll see what I can do.

**Comment by TrainerRoshi** [comment]
There is no more auto collection of contest chests as of 1.75. Just don't forget to collect them manually every 29 days or the pirates get them 🏴‍☠️
