### ISSUE TITLE
Champions

### ISSUE THREAD

**Issue by MrHoiable** [TrainerRoshi/Roshi-HHeroes-Trainer#6]
When I enable champions, the script keeps checking them even though I don't have any tickets.
It basically keeps looping: Main page > Champion page > Page of specific champions I selected > Main page (when the script sees i don't have any champion tickets)

**Comment by KevoNeo** [comment]
> When I enable champions, the script keeps checking them even though I don't have any tickets.
> It basically keeps looping: Main page > Champion page > Page of specific champions I selected > Main page (when the script sees i don't have any champion tickets)

I have exactly the same problem as MrHoiable!!!

**Comment by KevoNeo** [comment]
Hi, I see you updated the Script and added the new feature Places of Power, but I still have the same Bug in the Champions section when you don't have tickets, could you check that detail please. Beforehand thank you very much

**Comment by TrainerRoshi** [comment]
Fixed as of 1.13.0. The script will stop fighting Champions when you have 3 tickets or less. Feel free to donate if you want a smart system that picks the best girls for each champion.
