### ISSUE TITLE
Stuck in "My Harem"

### ISSUE THREAD

**Issue by sandorbihari** [TrainerRoshi/Roshi-HHeroes-Trainer#60]
Doesn't matter which browser I use start auto collect automatically, and is stuck in my Harem and do nothing!

**Comment by skars02** [comment]
Same problem. I have this error in the console log : 
jquery.min.js:2 Uncaught DOMException: Failed to set a named property on 'Storage': Setting the value of 'gMap' exceeded the quota.
    at autoLoop (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Master-Roshi's-HHeroes-Trainer.user.js&id=36d67491-ed49-47a3-a654-558bbecbe5aa:322:277384)

**Comment by TrainerRoshi** [comment]
Sorry about the delay. Fixed as of 1.70. There are so many girls that a variable got too big. Should be good for the next thousand girls now :)
