### ISSUE TITLE
Automatic collection in free daily/weekly/monthly bundle section

### ISSUE THREAD

**Issue by x0Trinity0x** [TrainerRoshi/Roshi-HHeroes-Trainer#63]
Hello, is it possible to turn off the option that the bot auto collects everything at once (especially the monthly one)? 15 combats seem to be not much but can be crucial in mythic day/revival events.

**Comment by x0Trinity0x** [comment]
Thanks for your answer. Sorry for the exaggeration, it wasn't meant to be like that. I only wish the weekly automatic collection could be turned off. Don't want to get slapped by 15 fists all of a sudden.

And btw, sorry for the off topic now, but when I select Dark Lord in the script, and then refresh the site or go to fight the said villain, the script deselects them. Only happens to Dark Lord, selecting the other villains work as intended. I cleared cache but to no avail. I don't know since when this bug exists.

Still many thanks to keep this script alive and I also respect the hard work you are putting in!

**Comment by Sarewe** [comment]
I would like to agree with X0Trinity0x. I also find it annoying when the daily and weekly bonus is collected without being asked. I would be happy if you can change that.

Thanks for the great work.

**Comment by TrainerRoshi** [comment]
@x0Trinity0x Yeah I see what you mean. It doesn't want to fight Dark Lord. Weird bug.

@Sarewe Not strange, I just haven't written code for daily/weekly/monthly collection in the other games. It's very complicated and I'm still not sure of the best way to do it.
