### ISSUE TITLE
Incorrect presentation in the event

### ISSUE THREAD

**Issue by Sarewe** [TrainerRoshi/Roshi-HHeroes-Trainer#64]
In the Agent 69 event, the rewards with Trainer Roshi are not displayed correctly. Everything overlaps and you can no longer recognise it. You can see it in the pictures. Once with trainer and once without.

![Screenshot 2024-01-08 112044](https://github.com/TrainerRoshi/Roshi-HHeroes-Trainer/assets/139480538/2139471d-8a49-4916-84cb-1448826534a6)
![Screenshot 2024-01-08 111950](https://github.com/TrainerRoshi/Roshi-HHeroes-Trainer/assets/139480538/dd944d9d-a771-41f3-9c6d-7034b71ac8d2)

**Comment by TrainerRoshi** [comment]
I'll fix it. It doesn't look that bad on mine. 
![Uploading Screenshot 2024-01-08 170950.jpg…]()

**Comment by TrainerRoshi** [comment]
Fixed as of 1.77. I also fixed the auto blessings. They changed the name of team edit URL.

**Comment by Sarewe** [comment]
A little better.
![Screenshot 2024-01-17 122731](https://github.com/TrainerRoshi/Roshi-HHeroes-Trainer/assets/139480538/7e6afe7d-744f-48e9-8b79-fd56dfa1bf87)

**Comment by TrainerRoshi** [comment]
I think you're using another script that is also nudging them closer together. Add this to the top of my script directly below `// ==/UserScript==`, above the comments, above the code: `GM_addStyle('.mega-tier-container { margin-right: 40px; }');` Change the `40px` until you're happy.

**Comment by Sarewe** [comment]
Yes, you're right. I use Hentai Heros ++. The problem only occurs when both are running together. When they run separately, the display is correct. But the way it is displayed after the last update is a good compromise for me. Thank you.

Changing the script did not work for me. I must have done something wrong.

**Comment by Sarewe** [comment]
Yes, you're right. I use Hentai Heros ++. The problem only occurs when both are running together. When they run separately, the display is correct. But the way it is displayed after the last update is a good compromise for me. Thank you.

Changing the script did not work for me. I must have done something wrong.
