### ISSUE TITLE
Girls in the foreground

### ISSUE THREAD

**Issue by Sarewe** [TrainerRoshi/Roshi-HHeroes-Trainer#65]
The girl on the start page is normally in the background. With Master Rashi it is placed in the foreground. Elements can be hidden in the process.

I also use another script that places buttons on the page. However, these buttons cannot be operated when the girl is in the foreground.

Can you undo the change that puts the girl in the foreground?
![Screenshot 2024-01-23 195719](https://github.com/TrainerRoshi/Roshi-HHeroes-Trainer/assets/139480538/36537c7b-9549-4f37-9a9f-8b53d61ff5cc)
![Screenshot 2024-01-23 195622](https://github.com/TrainerRoshi/Roshi-HHeroes-Trainer/assets/139480538/80f38be1-503a-4994-b296-3b0ca14a975d)

**Comment by TrainerRoshi** [comment]
Nope. I like it when the chick is in front of energy bar. Aren't the chicks the main reason we play? I made it so she is behind all the other buttons, like the quest button and the side quest button. The other script you are using must have very badly designed buttons.

**Comment by Sarewe** [comment]
Yes, it's certainly about the chicks. But your arrangement is a bit disadvantageous. With some girls you can no longer see the power display because the girl is standing in front of it and covering it up.

The other script is the "Hentai Heroes++ BDSM version". This is a very good scrip. I can go directly from the start page to the club, the labyrinth, etc. You can also change the pose of the girl on the start page without having to open the menu. 

The only problem is that the girl is in the foreground and hides the buttons. So I don't quite understand what the advantage is if the girl is in the foreground. For me, it's better if the girl is in the background so as not to disturb the other functions. Is there any way to change this?
![Screenshot 2024-01-31 114453](https://github.com/TrainerRoshi/Roshi-HHeroes-Trainer/assets/139480538/e2147e86-8883-4c77-851d-47432113a081)
![Screenshot 2024-01-31 114742](https://github.com/TrainerRoshi/Roshi-HHeroes-Trainer/assets/139480538/eccff90e-c261-4c5d-9c36-52b0df25b03c)

**Comment by TrainerRoshi** [comment]
So many ugly buttons. You should uninstall my script.
