### ISSUE TITLE
Collecting money dont work

### ISSUE THREAD

**Issue by Sarewe** [TrainerRoshi/Roshi-HHeroes-Trainer#66]
Collecting money no longer works for me since the last update of the game.

**Comment by TrainerRoshi** [comment]
I'll fix it. In the mean time you can make it work by manually going to the harem page.

**Comment by Sarewe** [comment]
That doesn't seem to work. I have installed the new version 1.79. But the money is not being collected. The harem is briefly displayed once and then left again immediately.

What is the girlfinder actually?

**Comment by TrainerRoshi** [comment]
Close and reopen your browser. The old localstorage needs to clear. You've never turned on Girl Finder to see what it does? Lame.

**Comment by Sarewe** [comment]
Thank you, the money collection is working again. Good work.

**Comment by Sarewe** [comment]
I suspect that the Girl Finder is adding girls to the harem that I already have 100 splitters of but haven't collected yet. Is that what it does? I'm afraid that's what the Girl Finder does. That's why I haven't switched it on. I want to decide for myself when I collect the girls. Because sometimes it's a task to get a new girl. But if I've already collected everything beforehand, I can't fulfil the task.

If I'm wrong here and the girl finder is doing something else, please let me know.

**Comment by TrainerRoshi** [comment]
Girl Finder simply fights trolls where you can win a girl. It resets every 24 hours in case of new events. It makes life easy during events where lots of trolls offer different girls.
