### ISSUE TITLE
Less than a second cooldown on money collection

### ISSUE THREAD

**Issue by Cyarutchiii** [TrainerRoshi/Roshi-HHeroes-Trainer#69]
Would it be possible to lower the cooldown to under a second?

I have over 350 Girls and it takes ages for it to collect everything, it's really annoying.

If not, could you please tell me the reason?

Thanks for your work :)

**Comment by TrainerRoshi** [comment]
Less than a second will probably get your account banned. They used to lock you out for five hours if it was less than a second. Sell items if you need the cash. At level 500 green gear sells for over a million each.
