### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Eznemazajatek** [TrainerRoshi/Roshi-HHeroes-Trainer#7]
Hi!

The game got updated and because it the trainer stopped working.
Can you update it please
Thanks!

**Comment by TrainerRoshi** [comment]
Try the new version; 1.10.0.

**Comment by KevoNeo** [comment]
Hi, When I enable champions, the script keeps checking them even though I don't have any tickets.
It basically keeps looping: Main page > Champion page > Page of specific champions I selected > Main page (when the script sees i don't have any champion tickets), could you check that detail please. Beforehand thank you very much

**Comment by njls20** [comment]
Hi, Trainerroshi!
The game got updated and because it Place of Power stopped working.
Can you update it, please? Thks!

**Comment by TrainerRoshi** [comment]
Updated to 1.13.0. Places of Power, Champions, Season of the Rose all work :)
