### ISSUE TITLE
The money is no longer collected automatically

### ISSUE THREAD

**Issue by Sarewe** [TrainerRoshi/Roshi-HHeroes-Trainer#74]
Unfortunately, the automatic collection of money no longer works. When you start the game, the harem is briefly opened and immediately closed again.

I use https://www.pornstarharem.com and https://www.hentaiheroes.com with Microsoft edge. I deleted the memory as indicated. But that didn’t change anything.

**Comment by Satevis15** [comment]
Hello, 
Same here :)

**Comment by TrainerRoshi** [comment]
Try update 1.82. Sorry about the delay.

**Comment by Sarewe** [comment]
Now it works again. Thank you very much.
