### ISSUE TITLE
POP breaks if you don't have all areas unlocked

### ISSUE THREAD

**Issue by soilaccountant** [TrainerRoshi/Roshi-HHeroes-Trainer#9]
Reaching Heroes University in the adventure is a requirement for the third area of POP. If you don't have it unlocked the trainer locks up trying to enter a locked zone.

Verified broken in V1.13.0

**Comment by TrainerRoshi** [comment]
Go to your POP screen, CTRL + SHIFT + i to open developer mode. ELEMENTS tab and CTRL + F to search for "STATUS". What is the status of your third POP? My code checks for "in_progress","pending_reward" and "can_start" but maybe I missed one.
![Screenshot 2020-11-12 142927](https://user-images.githubusercontent.com/48032437/98987067-ba871580-24f3-11eb-92bd-427eb5e1015b.png)

**Comment by soilaccountant** [comment]
It appears that locked zones don't have attributes on the div. Maybe you could filter for pop_thumb_greyed_out class... or the absence of the status attribute.

![image](https://user-images.githubusercontent.com/74081678/99013423-5705e380-2505-11eb-8728-6cea99c51f62.png)

**Comment by TrainerRoshi** [comment]
No problem :)
